#car:
joint_state_controller:
    type: /joint_state_controller/JointStateController
    publish_rate: 20

front_left_wheel_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: front_left_wheel_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

front_right_wheel_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: front_right_wheel_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

back_right_wheel_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: back_right_wheel_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

back_left_wheel_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: back_left_wheel_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}
/gazebo_ros_control:
    pid_gains:
        front_left_wheel_joint:
            p: 0.0
            i: 0.0
            d: 0.0
        front_right_wheel_joint:
            p: 0.0
            i: 0.0
            d: 0.0
        back_left_wheel_joint:
            p: 0.0
            i: 0.0
            d: 0.0
        back_right_wheel_joint:
            p: 0.0
            i: 0.0
            d: 0.0
