car:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    joint_f_r_wheel_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint_f_r_wheel
        pid: {p: 1.0, i: 1.0, d: 0.0}

    joint_b_r_wheel_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint_b_r_wheel
        pid: {p: 00.1, i: 0.00001, d: 0.0001}

    joint_f_l_wheel_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint_f_l_wheel
        pid: {p: 1.0, i: 1.0, d: 0.0}

    joint_b_l_wheel_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint_b_l_wheel
        pid: {p: 1.0, i: 1.0, d: 0.0}
