car_ns:
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

joint_f_r_wheel_position_controller:
    type: effor_controllers/JointPositionController
    joint: joint_f_r_wheel
    pid: {p: 1.0, i: 1.0, d: 0.0}

joint_b_r_wheel_position_controller:
    type: effor_controllers/JointPositionController
    joint: joint_b_r_wheel
    pid: {p: 0.0, i: 0.0, d: 0.0}

joint_f_l_wheel_position_controller:
    type: effor_controllers/JointPositionController
    joint: joint_f_l_wheel
    pid: {p: 1.0, i: 1.0, d: 0.0}

joint_b_l_wheel_position_controller:
    type: effor_controllers/JointPositionController
    joint: joint_b_l_wheel
    pid: {p: 1.0, i: 1.0, d: 0.0}
